version: 2.1
jobs:
  build:
    docker:
      - image: node
    steps:
      - run: echo "This job represents a typical build job"
  deploy:
    docker:
      - image: node
    steps:
      - run: echo "This job represents a typical deploy job"
  test:
    docker:
      - image: node
    steps:
      - run: echo "This job represents a typical test job"
orbs:
  sumologic: circleci/sumologic@1.0.2
workflows:
  build-test-and-deploy:
    jobs:
      - sumologic/workflow-collector
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
