experimental:
  pipelines: true
jobs:
  build:
    docker:
      - image: node
    steps:
      - run: echo "This job represents a typical build job"
  deploy:
    docker:
      - image: node
    steps:
      - run: echo "This job represents a typical deploy job"
  test:
    docker:
      - image: node
    steps:
      - run: echo "This job represents a typical test job"
orbs:
  sumologic: circleci/sumologic@1.0.2
version: 2.1
workflows:
  build-test-and-deploy:
    jobs:
      - sumologic/workflow-collector
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
#orbs:
#    hello: circleci/hello-build@0.0.5
#workflows:
#  Hello Workflow:
#    jobs:
#      - sumologic/workflow-collector
#      - hello/hello-build
